apiVersion: v1
kind: Service
metadata:
  labels:
    app: vm-app
    app.kubernetes.io/component: vm-app
    app.kubernetes.io/instance: vm-app
    app.kubernetes.io/name: vm-app
    app.kubernetes.io/part-of: app
  name: vm-app
  namespace: vm-apps
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    vm.kubevirt.io/name: vm-app